name: SHAREEFs-DEMO2  # Name of the workflow

on:
  push:  # Auto trigger when changes are pushed to develop branch
    branches:
      - develop

  # Optional: Uncomment if you want PR trigger to main
  pull_request:
    branches:
      - main  # Triggers when PR targets main branch

  workflow_dispatch:  # Manual trigger for ALL branches

jobs:
  job1-build:
    name: Build Phase
    runs-on: ubuntu-latest
    steps:
      # Step 1: Simple command
      - name: build-phase
        run: echo "Hello, world!"

      # Step 2: Multiple shell commands
      - name: multiple shell commands
        run: |
          echo "Listing files:"
          ls
          echo "Current directory:"
          pwd

  job2-test:
    name: Test Phase
    runs-on: ubuntu-latest
    needs: job1-build
    steps:
      - name: test-phase
        run: echo "Testing Done!"

  job3-deploy:
    name: Deploy Phase
    runs-on: ubuntu-latest
    needs: job2-test
    steps:

        # ✅ Here we are using the variable created in:
        # Settings → Secrets & Variables → Actions → Variables → USERNAME
        # Accessed using: ${{ vars.USERNAME }}

      - name: Print variable
        run: echo "Username is ${{ vars.USERNAME }}"
       # not prints the secret values and by default it masked in the logs and not expossed my outside the world!
      - name: Print secret
        run: echo "Docker Password is ${{ secrets.DOCKER_PASSWORD }}"

      - name: deploy-phase
        run: echo "Deployment Done!"

  
# Optional: Run only if triggered from develop branch
# ✅ Case 1: Push to develop
# ✅ Workflow runs
# ✅ This step also runs ✅
# Output:
# Triggered from develop branch ✅

# ✅ Case 2: Manual run on main
# ✅ Workflow runs
# ❌ This step will be SKIPPED

# ✅ Case 3: Manual run on develop
# ✅ Workflow runs
# ✅ This step runs
      - name: develop branch check
        if: github.ref == 'refs/heads/develop'
        run: echo "Triggered from develop branch ✅"

      # General info
      - name: print execution info
        run: echo "Workflow executed successfully 🚀"
        
