name: SHAREEFs-DEMO2 # name of the workflow
on: push
jobs:
  job1-build:
    runs-on: ubuntu-latest
    steps:
# single run
      - name: build-phase
        run: echo "Hello, world!"
# multiple shell commands executions    
      - name: multiple shell commands
        run: |
          ls
          pwd
# multiple jobs execution and its own runner(runs-on)
  job2-test:
    runs-on: ubuntu-latest
    needs: job1-build
    steps:
      - name: test-phase
        run: echo "Testing Done!"

  job3-deploy:
    runs-on: ubuntu-latest
    needs:
      - job2-test
    steps:
      - name: deploy-phase
        run: echo "Deployment Done!"
    
    

        
