name: Multiple Inputs Demo

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Enter your username"
        required: true
        default: "shareef"

      environment:
        description: "Select environment"
        required: true
        default: "dev"

      version:
        description: "Enter application version"
        required: false
        default: "v1.0"

      fruit:
        description: "Select your fav fruit"
        required: true
        type: choice           # ✅ Dropdown input
        options:
          - apple
          - banana
          - cherries

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print all inputs
        run: |
          echo "Username: ${{ github.event.inputs.username }}"
          echo "username is : ${{ inputs.username }}"
          
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "environment is : ${{ inputs.environment }}"
          
          echo "Version: ${{ github.event.inputs.version }}"
          echo "version is : ${{ inputs.version }}"
          
          echo "Fruit: ${{ github.event.inputs.fruit }}"
          echo "fruit is : ${{ inputs.fruit }}"
          
